source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target "KYVedioPlayer" do
pod 'Masonry', '~> 1.0.2'
pod 'MJRefresh', '~> 3.1.12'
pod 'SDWebImage', '~> 3.8.2'
pod 'MBProgressHUD', '~> 1.0.0'

end
